### ISSUE TITLE
private registry

### ISSUE THREAD

**Issue by adziubin** [hakdogan/jenkins-pipeline#2]
How can I add my own private registry to push \ pull images?

**Comment by hakdogan** [comment]
Hi @adziubin,

I didn't use a private registry and I'm not sure but I think, if you use the syntax that you use for local registry in commands such as pull/push in the Jenkins file, you will not encounter a problem. 

I'm sorry, maybe I couldn't help.

Contrary to my prediction if there is a problem and you reach a solution please share it.

**Comment by hakdogan** [comment]
Hello @adziubin

I'll close this issue because there is no response from you.
